version: '3.9'
services:
  web:
    build: ./app
    ports:
      - 8000
    restart: always
    environment:
      DEBUG: False
      SECRET_KEY: dlwabgkadawggdfvanbcAWD
      DATABASE_URL: postgresql://todo_admin:123123@postgres/todo_base
      DATABASE_USER: todo_admin
      DATABASE_PASSWORD: 123123
    depends_on: 
      - "postgres"
  postgres:
    image: postgres:15.2
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    restart: always
    environment:
      POSTGRES_USER: todo_admin
      POSTGRES_PASSWORD: 123123
      POSTGRES_DB: todo_base

volumes:
  postgres_data: